server:
  port: 8082
 
#for h2 database 
#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  h2:
#    console:
#      enabled: true 
#        
#  application:
#    name: employeeService
#    
#  datasource:
#    url: jdbc:h2:mem:testdb
#  for config server 
#spring:
#  application:
#    name: employeeService
#  config:
#    import: optional:configserver:http://localhost:8888
#for mysql database
spring:
  application:
    name: employeeService
  datasource:
#    url: jdbc:mysql://localhost:3306/mydb #?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # options are none, update, create, create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Update the dialect to MySQL8Dialect



